const char* g_copyrightText =
    "Ecode - Native Win32 Text Editor\r\n"
    "Copyright (c) 2025-2026 Ecode Team\r\n"
    "Licensed under the MIT License.\r\n"
    "\r\n"
    "Built with:\r\n"
    "  - Direct2D / DirectWrite\r\n"
    "  - Windows API (Win32)\r\n"
    "\r\n"
    "Third-Party Components:\r\n"
    "\r\n"
    "Duktape (JavaScript Engine)\r\n"
    "  Copyright (c) 2013-present Duktape authors\r\n"
    "  MIT License - https://duktape.org/\r\n"
    "\r\n"
    "libsixel (SIXEL Image Encoding/Decoding)\r\n"
    "  Copyright (c) 2014-2019 Hayaki Saito\r\n"
    "  MIT License\r\n"
    "  Sub-components:\r\n"
    "    - stb_image / stb_image_write by Sean Barrett (Public Domain)\r\n"
    "    - sixel original by kmiya (Permissive License)\r\n"
    "    - ppmquant/pnmcolormap by Jef Poskanzer, Bryan Henderson (Public Domain)\r\n"
    "    - sdump by haru (MIT License)\r\n"
    "    - Mesa OpenGL example code by Brian Paul (MIT License)\r\n"
    "\r\n"
    "Microsoft ConPTY / OpenConsole\r\n"
    "  Copyright (c) Microsoft Corporation\r\n"
    "  MIT License\r\n"
    "\r\n"
    "MIT VT420 Parser (reference implementation)\r\n"
    "  Copyright 1995 by the Massachusetts Institute of Technology\r\n"
    "  MIT License\r\n"
    "\r\n"
    "JSON for Modern C++ (nlohmann/json)\r\n"
    "  Copyright (c) 2013-2026 Niels Lohmann\r\n"
    "  MIT License\r\n"
    "\r\n"
    "yaml-cpp (YAML Parser)\r\n"
    "  Copyright (c) 2008-2022 Jesse Beder\r\n"
    "  MIT License\r\n"
    "\r\n"
    "md4c (Markdown Parser)\r\n"
    "  Copyright (c) 2016-2023 Martin Mitas\r\n"
    "  MIT License\r\n"
    "\r\n"
    "dukluv (Duktape + libuv scripting runtime)\r\n"
    "  Copyright (c) 2014 Tim Caswell\r\n"
    "  MIT License\r\n"
    "  Includes:\r\n"
    "    - libuv by Node.js contributors (MIT License)\r\n"
    "    - Duktape by Duktape authors (MIT License)\r\n"
    "\r\n"
    "Mbed TLS (used in LocalMsg)\r\n"
    "  Copyright The Mbed TLS Contributors\r\n"
    "  Apache License 2.0 OR GPL-2.0-or-later\r\n"
    "\r\n"
    "IPMsg (IP Messenger) (used in LocalMsg)\r\n"
    "  Copyright (c) 1996-2026 SHIROUZU Hiroaki\r\n"
    "  Copyright (c) 2015-2018 Asahi Net, Inc.\r\n"
    "  Copyright (c) 2018-2026 FastCopy Lab, LLC.\r\n"
    "  BSD 2-Clause License\r\n"
    "\r\n"
    "LocalSend (used in LocalMsg)\r\n"
    "  Copyright (c) 2022-2026 Tien Do Nam\r\n"
    "  Apache License 2.0\r\n"
    "\r\n"
    "Microsoft WebView2 SDK (used in Prompts)\r\n"
    "  Copyright (c) Microsoft Corporation\r\n"
    "  BSD 3-Clause License\r\n"
    "\r\n"
    "Cytoscape.js (used in Prompts)\r\n"
    "  Copyright (c) 2016-2025, The Cytoscape Consortium\r\n"
    "  MIT License\r\n"
    "\r\n"
    "mark.js (used in Prompts)\r\n"
    "  Copyright (c) 2014-2018 Julian Kühnel\r\n"
    "  MIT License\r\n"
    "\r\n"
    "marked (used in Prompts)\r\n"
    "  Copyright (c) 2011-2025 Christopher Jeffrey\r\n"
    "  MIT License\r\n"
    "\r\n"
    "mermaid (used in Prompts)\r\n"
    "  Copyright (c) 2014-present Knut Sveidqvist / Mermaid Contributors\r\n"
    "  MIT License\r\n"
    "\r\n"
    "24x24 Free Application Icons\r\n"
    "  Copyright (c) 2009 Aha-Soft\r\n"
    "  Creative Commons Attribution 3.0 US\r\n";
