const char* g_copyrightText =
    "Ecode - Native Win32 Text Editor\n"
    "Copyright (c) 2025 Ecode Team\n"
    "Licensed under the MIT License.\n"
    "\n"
    "Built with:\n"
    "  - Direct2D / DirectWrite\n"
    "  - Windows API (Win32)\n"
    "\n"
    "Third-Party Components:\n"
    "\n"
    "Duktape (JavaScript Engine)\n"
    "  Copyright (c) 2013-present Duktape authors\n"
    "  MIT License - https://duktape.org/\n"
    "\n"
    "libsixel (SIXEL Image Encoding/Decoding)\n"
    "  Copyright (c) 2014-2019 Hayaki Saito\n"
    "  MIT License\n"
    "  Sub-components:\n"
    "    - stb_image / stb_image_write by Sean Barrett (Public Domain)\n"
    "    - sixel original by kmiya (Permissive License)\n"
    "    - ppmquant/pnmcolormap by Jef Poskanzer, Bryan Henderson (Public Domain)\n"
    "    - sdump by haru (MIT License)\n"
    "    - Mesa OpenGL example code by Brian Paul (MIT License)\n"
    "\n"
    "Microsoft ConPTY / OpenConsole\n"
    "  Copyright (c) Microsoft Corporation\n"
    "  MIT License\n"
    "\n"
    "MIT VT420 Parser (reference implementation)\n"
    "  Copyright 1995 by the Massachusetts Institute of Technology\n"
    "  MIT License\n"
    "\n"
    "JSON for Modern C++ (nlohmann/json)\n"
    "  Copyright (c) 2013-2026 Niels Lohmann\n"
    "  MIT License\n"
    "\n"
    "yaml-cpp (YAML Parser)\n"
    "  Copyright (c) 2008-2022 Jesse Beder\n"
    "  MIT License\n"
    "\n"
    "md4c (Markdown Parser)\n"
    "  Copyright (c) 2016-2023 Martin Mitas\n"
    "  MIT License\n"
    "\n"
    "24x24 Free Application Icons\n"
    "  Copyright (c) 2009 Aha-Soft\n"
    "  Creative Commons Attribution 3.0 US\n";
